version: 2.1
defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:lts
orbs:
    node: circleci/node@1.1.6
    # jq: circleci/jq@2.0.2
jobs:
    build-and-test:
        <<: *defaults
        executor:
            name: node/default
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run: yarn
            - run:
                  name: Run tests
                  command: yarn test
            - run:
                  name: Build
                  command: yarn build
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - persist_to_workspace:
                  root: ~/repo
                  paths: .
    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Authenticate with registry
                  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - run:
                  name: Publish package
                  command: yarn publish --non-interactive
workflows:
    build-test-deploy:
        jobs:
            - build-and-test:
                  filters:
                      branches:
                          only: /^(master|deploy)$/
            - deploy:
                  requires:
                      - build-and-test
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
