version: 2.1
defaults: &defaults
    docker:
        - image: circleci/node:lts
orbs:
    node: circleci/node@1.1.6
    jq: circleci/jq@2.0.2
jobs:
    build-and-test:
        <<: *defaults
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: yarn
                      - run: yarn build
                      - run: yarn test
    deploy:
        <<: *defaults
        steps:
            - run:
                  name: Authenticate with registry
                  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - run:
                  name: Publish package
                  command: yarn publish --non-interactive
workflows:
    build-test-deploy:
        jobs:
            - build-and-test
            - deploy:
                  filters:
                      branches:
                          only: deploy
